### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by BlueNightSky** [Stanzilla/Kui_Stanzilla#1]
Hi !
The following error occurred when I logged in:
`1x Kui_Nameplates\messages.lua:540: Out of date plugin `ColourBarByName` ignored
[C]: in function `error'
Kui_Nameplates\messages.lua:540: in function `NewPlugin'
...faceKui_Stanzilla\kui.colour-bar-by-name.lua:8: in main chunk

Locals:
(*temporary) = "Out of date plugin `ColourBarByName` ignored"
`
Not only this error, I just use this as an example
I used these latest KuiNameplates after version 2.18.2 to get these errors.
(Sorry, English is very bad.)

**Comment by Stanzilla** [comment]
Yeah there has been a change in Kui and not all plugins are updated yet, I will push an update soon!

**Comment by Stanzilla** [comment]
Fixed in the latest release, sorry for the wait!
