### ISSUE TITLE
Target name... broken?

### ISSUE THREAD

**Issue by zkekahs2** [Stanzilla/Kui_Stanzilla#4]
![오류](https://user-images.githubusercontent.com/28775453/105131828-0f1ac280-5b2d-11eb-9ccc-9e57c3ba1547.JPG)

Hello I am a user playing in Korea

An error occurred while using the target name function.

Only targets with spaces are having problems.

Can you ask for an amendment?

----
ㅁ...name
----

**Comment by Stanzilla** [comment]
Oh hrm, looks like the shortening function is failing on unicode, I'll take a look!

**Comment by zkekahs2** [comment]
> Oh hrm, looks like the shortening function is failing on unicode, I'll take a look!

Thanks for letting me know it's a Unicode issue.
I solved it through search
https://www.wowinterface.com/forums/showthread.php?t=46497

Change code
kui.target-name.lua 27line

unitName = unitName:gsub("(%S+) ",function(t) return t:sub(1,1).."." end)

unitName = unitName:gsub("(.[\128-\191]*)%S+%s","%1.")
