### ISSUE TITLE
[Question] How to enable just some of the options?

### ISSUE THREAD

**Issue by wheatbread** [Stanzilla/Kui_Stanzilla#5]
I'd actually like to just enable the target option and disable the others, as I'm running Kui Target Helper which covers most of them.  Is there a way I can do so?

**Comment by Stanzilla** [comment]
Hey there! Sadly that's a bit of a manual process at, you would have to delete the files of the modules that you do not want or remove them from the TOC here https://github.com/Stanzilla/Kui_Stanzilla/blob/main/Kui_Stanzilla/Kui_Stanzilla.toc#L5

**Comment by wheatbread** [comment]
Gotcha, thank you!  I'll do that.
