### ISSUE TITLE
I cant get this addon to work for DF

### ISSUE THREAD

**Issue by ZynnlolGaming** [Stanzilla/Kui_Stanzilla#6]
I install the addon but it doesnt seem to have any option pop up in KUI Nameplate option at all or do i have to put it somewhere else ?

**Comment by Stanzilla** [comment]
It does not have any options, no. Everything you can change would be changed through the files itself

**Comment by ZynnlolGaming** [comment]
> It does not have any options, no. Everything you can change would be changed through the files itself

Ahh i see Thank for the quick reply also I installed the addon log in game and nothing happen, i didnt see any of the stuff your showed in CurseForge screen shot. Is there a guide somewhere on what to do and stuff ? I just want KUI Target nameplate to show who it attacking/casting the spell to
